#### AWA 配置(必需) ####
awaCookie: '' # 外星人论坛Cookie, 可以只有`REMEMBERME`, 没有`REMEMBERME`则必须有`PHPSESSID`和`sc`, 但会导致连续签到天数获取错误，不会影响其他功能
awaHost: 'www.alienwarearena.com' # 外星人论坛Host, 默认的没问题就不要改
awaUserId: '' # 外星人论坛用户Id
awaBorderId: '' # 外星人论坛当前的BorderId
awaBadgeIds: '' # 外星人论坛当前的BadgeIds
awaAvatar: '' # 外星人论坛当前的Avatar
awaBoosterNotice: true # 外星人论坛任务大于1个时询问是否开启助推器，助推器需要自行开启！！！
awaQuests:
  - dailyQuest # 自动做每日任务，不需要做此任务删除或注释掉此行
  - timeOnSite # 自动做AWA在线任务，不需要做此任务删除或注释掉此行
  - watchTwitch # 自动做Twitch直播间在线任务，不需要做此任务删除或注释掉此行
  - steamQuest # 自动做Steam游戏时长任务，不需要做此任务删除或注释掉此行

#### Twitch 配置 ####
twitchCookie: '' # Twitch Cookie, 须包括`unique_id` 和 `auth-token`


#### Steam 任务配置 ####
steamUse: 'ASF' # 'ASF'或'SU','SU'为模拟Steam客户端
#### ASF 配置 (此配置与Steam 配置二选一) ####
# steamUse为'ASF'时此配置有效
asfProtocol: 'http'
asfHost: '127.0.0.1'
asfPort: '1242'
asfPassword: ''
asfBotname: ''
#### Steam 配置 (此配置与ASF 配置二选一) ####
# steamUse为'SU'时此配置有效
steamAccountName: ''
steamPassword: ''

#### 代理设置(可选) ####
proxy:
  enable:
    - github # 在检测更新时使用代理，不使用删掉此行
    - twitch # 在访问Twitch站点时使用代理，不使用删掉此行
    - awa # 在访问外星人论坛站点时使用代理，不使用删掉此行
    - asf # 在访问ASF时使用代理，不使用删掉此行
    - steam # 在访问Steam时使用代理，不使用删掉此行
  protocol: 'http' # 代理协议，'http'|'https'|'socks4'|'socks5'
  host: '127.0.0.1' # 代理host
  port: 1080 # 代理端口
  username: '' # 代理用户名，没有可留空
  password: '' # 代理密码，没有可留空
