name: Docker

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  version: 2.4.8

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hclonely/awa-helper:latest
            hclonely/awa-helper:${{ env.version }}
      -
        name: Build and push with chromium
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.chromium
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hclonely/awa-helper-chromium:latest
            hclonely/awa-helper-chromium:${{ env.version }}
