name: Release
on:
  workflow_dispatch:
env:
  version: 2.4.7
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
      - run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          tag_name: v${{ env.version }}
          name: ${{ env.version }}
          body_path: CHANGELOG.txt
          files: |
            AWA-Helper.zip
            AWA-Helper.tar.gz
#            AWA-Manager.zip
#            AWA-Manager.tar.gz
          token: ${{ github.TOKEN }}
