name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          tag_name: v1.0.15
          name: 1.0.15
          body: |-
            - 添加配置项[awaBoosterNotice]: `true` | `false` 外星人论坛任务大于1个时询问是否开启助推器，助推器需要自行开启！！！
          files: AWA-Helper.zip
          token: ${{ github.TOKEN }}
