name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          tag_name: v1.0.9
          name: 1.0.9
          body: '- 添加检测更新功能 & 修复BUG'
          files: AWA-Helper.zip
          token: ${{ github.TOKEN }}
